app_name: Note App
app_version: 0.0.1
win_width: 1024
win_height: 710
min_win_width: 1024
min_win_height: 710
frameless: false
maximixed: false
fixed_size: false
Debug: true
render_dir: render
assets_dir: assets
assets_server_port: 8002
app_id: com.pythra.note-app
