app_name: Note App
win_width: 1024
win_height: 700
min_win_width: 1024
min_win_height: 700
frameless: false
maximixed: false
fixed_size: false
Debug: true
render_dir: render
assets_dir: assets
assets_server_port: 8004

